server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gpw1126/microservice.git #GitHub上面的git仓库名字
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

